name: Run Main Script Weekly

on:
  schedule:
    # Run every week at 00:00 UTC on Monday
    - cron: "0 0 * * 1"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run the root main.py
      - name: Run main.py
        run: |
          source .venv/bin/activate
          python main.py

      # Step 5: Commit the updated image
      - name: Commit and push changes
        run: |
          git config --local user.email "p.sky002@gmail.com"
          git config --local user.name "creatorsky"
          git add -u
          git commit -m "Weekly update [skip ci]"
          git push
