name: Run Main Script Weekly

on:
  schedule:
    # Run every week at 00:00 UTC on Monday
    - cron: "0 0 * * 1"
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      # Step 4: Run the root immix.py script
      - name: Run immix.py
        run: |
          source .venv/bin/activate
          python immix.py

      # Step 5: Commit and push changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "p.sky002@gmail.com"
          git config --local user.name "creatorsky"
          git add -u
          git commit -m "Weekly update [skip ci]" || echo "No changes to commit"
          git push
